Repository Emethium/farquest, pull requests merged in 2019-08, with the labels that each got.

#1 Refact/node
  .env.example
  .eslintrc.json
  .gitignore
  .prettierrc.json
  package-lock.json
  package.json
  src/config/environment.js
  src/index.js
  src/lambda.py
  src/util/index.js
Labels: enhancement

#2 Docs/readme
  .env.example
  README.md
  src/config/environment.js
  src/index.js
  src/util/index.js
Labels: documentation, enhancement

#4 fix(core): removed aws credentials and imported http on network modul…
  src/config/environment.js
  src/core/network.js
Labels: bug

#5 Feat/health check
  .env.example
  package-lock.json
  package.json
  src/config/environment.js
  src/core/index.js
  src/core/network.js
  src/core/task.js
  src/index.js
Labels: enhancement

#6 Feat/parse event source
  package-lock.json
  package.json
  src/core/network.js
  src/index.js
  src/util/index.js
  src/util/message.js
  tests/samples/event.json
  tests/samples/payload.json
Labels: enhancement

#7 docs(core/network,core/tasks,core/message): renamed functions to decouple BL
  .gitignore
  README.md
  jsdoc.json
  package-lock.json
  package.json
  src/config/environment.js
  src/core/index.js
  src/core/network.js
  src/core/task.js
  src/index.js
  src/util/index.js
  src/util/message.js
  tests/samples/event.json
Labels: documentation
